// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refresh_tokens.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (user_id, token_hash, family, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, token_hash, family, revoked, expires_at, created_at
`

type CreateRefreshTokenParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	Family    pgtype.UUID        `json:"family"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

// CreateRefreshToken
//
//	INSERT INTO refresh_tokens (user_id, token_hash, family, expires_at)
//	VALUES ($1, $2, $3, $4)
//	RETURNING id, user_id, token_hash, family, revoked, expires_at, created_at
func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken,
		arg.UserID,
		arg.TokenHash,
		arg.Family,
		arg.ExpiresAt,
	)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Family,
		&i.Revoked,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredTokens = `-- name: DeleteExpiredTokens :exec
DELETE FROM refresh_tokens
WHERE expires_at < now()
`

// DeleteExpiredTokens
//
//	DELETE FROM refresh_tokens
//	WHERE expires_at < now()
func (q *Queries) DeleteExpiredTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredTokens)
	return err
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT id, user_id, token_hash, family, revoked, expires_at, created_at FROM refresh_tokens
WHERE token_hash = $1
LIMIT 1
`

// GetRefreshTokenByHash
//
//	SELECT id, user_id, token_hash, family, revoked, expires_at, created_at FROM refresh_tokens
//	WHERE token_hash = $1
//	LIMIT 1
func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Family,
		&i.Revoked,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const revokeAllUserTokens = `-- name: RevokeAllUserTokens :exec
UPDATE refresh_tokens
SET revoked = true
WHERE user_id = $1 AND revoked = false
`

// RevokeAllUserTokens
//
//	UPDATE refresh_tokens
//	SET revoked = true
//	WHERE user_id = $1 AND revoked = false
func (q *Queries) RevokeAllUserTokens(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllUserTokens, userID)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens
SET revoked = true
WHERE id = $1
`

// RevokeRefreshToken
//
//	UPDATE refresh_tokens
//	SET revoked = true
//	WHERE id = $1
func (q *Queries) RevokeRefreshToken(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, id)
	return err
}

const revokeTokenFamily = `-- name: RevokeTokenFamily :exec
UPDATE refresh_tokens
SET revoked = true
WHERE family = $1
`

// RevokeTokenFamily
//
//	UPDATE refresh_tokens
//	SET revoked = true
//	WHERE family = $1
func (q *Queries) RevokeTokenFamily(ctx context.Context, family pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeTokenFamily, family)
	return err
}
