// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activateUser = `-- name: ActivateUser :exec
UPDATE users
SET is_active = true, updated_at = now()
WHERE id = $1
`

// ActivateUser
//
//	UPDATE users
//	SET is_active = true, updated_at = now()
//	WHERE id = $1
func (q *Queries) ActivateUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, activateUser, id)
	return err
}

const countActiveAdmins = `-- name: CountActiveAdmins :one
SELECT COUNT(*) FROM users u
JOIN user_roles ur ON ur.user_id = u.id
JOIN roles r ON r.id = ur.role_id
WHERE r.name = 'admin' AND u.is_active = true
`

// CountActiveAdmins
//
//	SELECT COUNT(*) FROM users u
//	JOIN user_roles ur ON ur.user_id = u.id
//	JOIN roles r ON r.id = ur.role_id
//	WHERE r.name = 'admin' AND u.is_active = true
func (q *Queries) CountActiveAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveAdmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password)
VALUES ($1, $2)
RETURNING id, email, password, is_active, created_at, updated_at
`

type CreateUserParams struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// CreateUser
//
//	INSERT INTO users (email, password)
//	VALUES ($1, $2)
//	RETURNING id, email, password, is_active, created_at, updated_at
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.Password)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateUser = `-- name: DeactivateUser :exec
UPDATE users
SET is_active = false, updated_at = now()
WHERE id = $1
`

// DeactivateUser
//
//	UPDATE users
//	SET is_active = false, updated_at = now()
//	WHERE id = $1
func (q *Queries) DeactivateUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deactivateUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password, is_active, created_at, updated_at FROM users
WHERE email = $1 AND is_active = true
LIMIT 1
`

// GetUserByEmail
//
//	SELECT id, email, password, is_active, created_at, updated_at FROM users
//	WHERE email = $1 AND is_active = true
//	LIMIT 1
func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password, is_active, created_at, updated_at FROM users
WHERE id = $1 AND is_active = true
LIMIT 1
`

// GetUserByID
//
//	SELECT id, email, password, is_active, created_at, updated_at FROM users
//	WHERE id = $1 AND is_active = true
//	LIMIT 1
func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserPermissions = `-- name: GetUserPermissions :many
SELECT DISTINCT
    CAST(p.action || ':' || p.resource AS TEXT) AS permission
FROM users u
JOIN user_roles ur ON ur.user_id = u.id
JOIN role_permissions rp ON rp.role_id = ur.role_id
JOIN permissions p ON p.id = rp.permission_id
WHERE u.id = $1 AND u.is_active = true
`

// GetUserPermissions
//
//	SELECT DISTINCT
//	    CAST(p.action || ':' || p.resource AS TEXT) AS permission
//	FROM users u
//	JOIN user_roles ur ON ur.user_id = u.id
//	JOIN role_permissions rp ON rp.role_id = ur.role_id
//	JOIN permissions p ON p.id = rp.permission_id
//	WHERE u.id = $1 AND u.is_active = true
func (q *Queries) GetUserPermissions(ctx context.Context, id pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, getUserPermissions, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var permission string
		if err := rows.Scan(&permission); err != nil {
			return nil, err
		}
		items = append(items, permission)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, is_active, created_at, updated_at FROM users
ORDER BY created_at DESC
`

type ListUsersRow struct {
	ID        pgtype.UUID        `json:"id"`
	Email     string             `json:"email"`
	IsActive  bool               `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// ListUsers
//
//	SELECT id, email, is_active, created_at, updated_at FROM users
//	ORDER BY created_at DESC
func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserPassword = `-- name: UpdateUserPassword :one
UPDATE users
SET password = $2, updated_at = now()
WHERE id = $1
RETURNING id, email, password, is_active, created_at, updated_at
`

type UpdateUserPasswordParams struct {
	ID       pgtype.UUID `json:"id"`
	Password string      `json:"password"`
}

// UpdateUserPassword
//
//	UPDATE users
//	SET password = $2, updated_at = now()
//	WHERE id = $1
//	RETURNING id, email, password, is_active, created_at, updated_at
func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserPassword, arg.ID, arg.Password)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
